[build]
  command = "npm run build"
  publish = ".next"
  functions = "out_functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
